### ISSUE TITLE
Warning  UnexpectedAdmissionErro

### ISSUE THREAD

**Issue by GLL550C** [volcano-sh/devices#17]
运行pod报错 Warning  UnexpectedAdmissionError  79s   kubelet  Allocate failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected @ @

>

**Comment by GLL550C** [comment]
@Jeffwan

**Comment by Thor-wl** [comment]
/bug
This bug has also been mentioned in the Volcano wechat group.

**Comment by Thor-wl** [comment]
Can you give the reproduce steps and environment? Let me take a try.

**Comment by WingkaiHo** [comment]
If you have use nvidia-smi to hide gpu, index will be change, number of device will be decrease. Such as
```
nvidia-smi drain -p <id> -m 0
```
id of gpu devices never delete in scheduler when number gpu decrease
https://github.com/volcano-sh/volcano/pull/2215

**Comment by WingkaiHo** [comment]
If you have use nvidia-smi to hide gpu, index will be change, number of device will be decrease. Such as
```
nvidia-smi drain -p <id> -m 0
```

Or some gpu is damage，it disable by drive, such as
![device2](https://user-images.githubusercontent.com/14209014/186844384-bbc0e178-d7ce-4f70-af78-11b5fc012f0f.jpg)

but is still in path dev path 
![device1](https://user-images.githubusercontent.com/14209014/186855407-d64086b6-fb47-4019-b99f-bed7de81ed73.jpg)


When use nvidia-smi to hide gpu, for example is hide /dev/nvidia0, device plugin init 
```
        deviceByIndex := map[uint]string{}
	for i := uint(0); i < n; i++ {
		d, err := nvml.NewDevice(i)
		check(err)
		var id uint
		_, err = fmt.Sscanf(d.Path, "/dev/nvidia%d", &id)
		check(err)
		deviceByIndex[id] = d.UUID
		// TODO: Do we assume all cards are of same capacity
	}
```

so device plugint do not have index 0 gpu, but scheduler start gpu index is 0, so if will fail to   Warning UnexpectedAdmissionError 79s kubelet Allocate failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected error

**Comment by 631068264** [comment]
same issue https://github.com/volcano-sh/volcano/issues/2701  use Volcano  1.7   and https://github.com/volcano-sh/devices/blob/release-1.0/volcano-device-plugin.yml

I did not use
```
nvidia-smi drain -p <id> -m 0
```
